Updating variables in Celldet
AMReX-Astro/Castro pull request #1925
Opened 2021-07-02 13:57 UTC by Ishita-S

## PR summary

## PR motivation

## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

2021-07-02 14:08 UTC, harpolea requested changes

2021-07-02 14:08 UTC, harpolea commented on Exec/science/celldet/problem_initialize.H
> +    eos_state.rho = problem::rho_fuel;
```suggestion
    eos_state.rho = problem::dens_fuel;
```

2021-07-02 14:08 UTC, harpolea commented on Exec/science/celldet/problem_initialize.H
> +    eos_state.rho = problem::rho_fuel;  // initial guess
```suggestion
    eos_state.rho = problem::dens_fuel;  // initial guess
```

2021-07-02 14:08 UTC, harpolea commented on Exec/science/celldet/problem_initialize.H
> +    problem::mass_flux = problem::rho_fuel * problem::v_inflow;
```suggestion
```
We don't need the mass flux for this problem

2021-07-02 14:08 UTC, harpolea commented on Exec/science/celldet/problem_initialize.H
> +    problem::rho_ash = eos_state.rho;
```suggestion
    problem::dens_ash = eos_state.rho;
```

2021-07-02 14:08 UTC, harpolea commented on Exec/science/celldet/problem_initialize.H
>      // get the species indices
I'm not convinced you actually need any of the stuff from this point onwards

2021-07-02 14:08 UTC, harpolea commented on Exec/science/celldet/problem_initialize_state_data.H
>      for (int n = 0; n < NumSpec; n++) {
```suggestion
```
You don't need to have these in separate loops

2021-07-03 15:20 UTC, zingale commented on Exec/science/celldet/inputs.celldet
> +problem.T_r = 2.e8
you renamed these to T_ash and T_fuel, and similarly rho_ash and rho_fuel, so you need to update the inputs

2021-07-03 15:21 UTC, zingale commented on Exec/science/celldet/_prob_params
>  cfrac                real          0.5_rt         y
is cfrac used still?

2021-07-06 16:15 UTC, zingale commented on Exec/science/celldet/inputs.celldet
can you remove these merge conflict lines?

2021-07-06 16:15 UTC, zingale commented on Exec/science/celldet/nse19.tbl
> +../../../external/Microphysics/networks/aprox19/nse19.tbl
this file should not be part of the PR

2021-07-06 16:18 UTC, zingale commented on Exec/science/celldet/problem_initialize_state_data.H
> +>>>>>>> cff4ab0ffa9e10c81e2cbec9a2be8d68e661b136
you need to remove / resolve this merge conflict

2021-07-06 16:18 UTC, zingale commented on Exec/science/celldet/species_diag.out
> +#   COLUMN 1                        2                        3                        4                        5                        6                        7                        8
this file should not be part of the PR

2021-07-06 16:19 UTC, zingale commented
can you merge the latest `development` into the PR?

2021-07-06 16:32 UTC, zingale commented on Exec/science/celldet/problem_initialize_state_data.H
> +=======
this is left behind from a merge

2021-07-06 16:32 UTC, zingale commented on Exec/science/celldet/amr_diag.out
> +#   COLUMN 1                        2                        3           4                        5
this file should not be part of the PR

2021-07-06 16:33 UTC, zingale commented on Exec/science/celldet/grid_diag.out
> +                     time                     mass                     xmom                     ymom                     zmom                ang mom x                ang mom y                ang mom
this file should not be part of the PR

2021-07-06 16:34 UTC, zingale commented
I think you might need to pull in the submodules?  I am not sure why it wants to update amrex and Microphysics, but those should not be part of this PR

2021-07-06 16:37 UTC, Ishita-S commented
Does the most recent commit I made resolve the issue?

2021-07-06 16:41 UTC, zingale commented
it looks like the files are still there.

2021-07-06 16:49 UTC, Ishita-S commented
I manually deleted them one GitHub so hopefully that clears that issue

2021-07-14 18:29 UTC, closed without merging